### ISSUE TITLE
Add Config To Silently Fail On Missing AKV Secrets

### ISSUE THREAD

**Issue by dolenox** [Azure/secrets-store-csi-driver-provider-azure#566] opened 2021-07-08 20:34 UTC
**Describe the solution you'd like**
When the CSI driver is unable to locate a secret (due to it being deleted or disabled), silently fail (with warning log) instead of blocking pod startup. 

**Anything else you would like to add:**
We would prefer to fail in runtime than on startup. We had an issue where we deleted an unused secret from our key vault and it impacted our production services. Ideally, we wouldn't have had any impact here, since the secret was not required.

**Comment by aramase** [comment] 2021-08-16 22:34
Duplicate of https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/567

**Closed by aramase** 2021-08-16 22:34 UTC
Labels: enhancement
