### ISSUE TITLE
unable to deploy the 2 apps

### ISSUE THREAD

**Issue by kanukhosla** [Azure/secrets-store-csi-driver-provider-azure#322] opened 2020-11-22 20:34 UTC
Got this error while deploying app1 and app2
![image](https://user-images.githubusercontent.com/57665232/99916358-b78fe000-2cbe-11eb-8e9a-9e7674bb14b6.png)

This my secret 
![image](https://user-images.githubusercontent.com/57665232/99916384-dd1ce980-2cbe-11eb-8134-e6685cb1810a.png)

This is my SecretProviderClass file:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: spc-tls-test1
spec:
  provider: azure
  secretObjects:                              
  - secretName: secrets-store-driver-test1          
    type: kubernetes.io/tls
    data:
    - objectName: ingress-tls-test1
      key: tls.key
    - objectName: ingress-tls-test1
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    keyvaultName: ingress-tls-vault-test1                      
    objects: |
      array:
        - |
          objectName: ingress-tls-test1
          objectType: secret
    tenantId: <directory id of my key vault >
```

Not sure here if my object type should be secret or certificate or something else. 

and I also granted the service principal permissions to get secrets:
az keyvault set-policy -n $KV_NAME --certificate-permissions get --spn <YOUR SPN CLIENT ID>

Can you please help me resolve my issue . 
thanks in advance.

**Comment by kanukhosla** [comment] 2020-11-22 20:38
This is my SecretProviderClass file:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: spc-tls-test1
spec:
  provider: azure
  secretObjects:                              
  - secretName: secrets-store-driver-test1          
    type: kubernetes.io/tls
    data:
    - objectName: ingress-tls-test1
      key: tls.key
    - objectName: ingress-tls-test1
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    keyvaultName: ingress-tls-vault-test1                      
    objects: |
      array:
        - |
          objectName: ingress-tls-test1
          objectType: secret
    tenantId: <directory id of my key vault >
```


Not sure here if my object type should be secret or certificate or something else.

**Comment by aramase** [comment] 2020-11-23 17:29
@kanukhosla Could you please provide more info on the versions being used and also the auth method? If not using service principal mode, remove the following snippet from the deployment yamls as noted in the documentation:
```
            nodePublishSecretRef:
              name: secrets-store-creds
```

**Comment by kanukhosla** [comment] 2020-11-23 17:48
I revisited my steps and I guess my ingress controller never got deployed. 

```
$ helm install ingress-nginx/ingress-nginx --generate-name \
>     --namespace ingress-tls-test1 \
>     --set controller.replicaCount=2 \
>     --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
>     --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
Error: failed to download "ingress-nginx/ingress-nginx" (hint: running `helm repo update` may help)
```

I don't think this should however prevent me from deploying the application. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-app-one
  labels:
    app: ingress-app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-app-one
  template:
    metadata:
      labels:
        app: ingress-app-one
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: secrets-store-inline-vol1
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline-vol1
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "spc-tls-test1"
            nodePublishSecretRef:
              name: secrets-store-driver-test1
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-app-one
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ingress-app-one
```

and I am using service principal in this demo. 

Thanks for your time.

**Comment by aramase** [comment] 2020-11-23 19:09
Glad the issue is resolved. Closing this issue now. Please feel free to open a new issue if you have any questions.

**Comment by kanukhosla** [comment] 2020-11-23 19:10
Sorry the issue is not closed

**Comment by aramase** [comment] 2020-11-23 19:13
@kanukhosla If using `ServicePrincipal` auth method did you create the kubernetes secret with `clientid` and `clientsecret`? The error message you posted above shows `clientid` is empty.

**Comment by kanukhosla** [comment] 2020-11-23 19:18
@aramase as

> @kanukhosla If using `ServicePrincipal` auth method did you create the kubernetes secret with `clientid` and `clientsecret`? The error message you posted above shows `clientid` is empty.

as mentioned in my original post is used the below command to grant the service principal permissions to get secrets:

`az keyvault set-policy -n $KV_NAME --certificate-permissions get --spn`

also do you know why I am unable to install the ingress controller in the new namespace ? I installed the ingress controller in a different namespace earlier

**Comment by aramase** [comment] 2020-11-23 19:22
@kanukhosla The Kubernetes secret created with the `ServicePrincipal` credentials is missing the `clientid`: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/service-principal-mode.md#service-principal

```
# Client ID (AZURE_CLIENT_ID) will be the App ID of your service principal
# Client Secret (AZURE_CLIENT_SECRET) will be the Password of your service principal

kubectl create secret generic secrets-store-creds --from-literal clientid=<AZURE_CLIENT_ID> --from-literal clientsecret=<AZURE_CLIENT_SECRET>
```

**Comment by kanukhosla** [comment] 2020-11-23 19:49
thanks that helped. I executed that command earlier but I didn't edit my client id instead I just put clientid=$AZURE_CLIENT_ID .

Now I need to install the ingress controller. I am getting the below error . I am not sure if I can have multiple ingress controllers in different namespaces. I was able to install an ingress controller earlier in a different namespace though. 

```
$ helm install ingress-nginx/ingress-nginx --generate-name \
>     --namespace ingress-tls-test1 \
>     --set controller.replicaCount=2 \
>     --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
>     --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
Error: failed to download "ingress-nginx/ingress-nginx" (hint: running `helm repo update` may help)
```

@aramase

**Comment by aramase** [comment] 2020-11-23 20:03
@kanukhosla For ingress controller issues I would recommend checking the issues in the `ingress-nginx` repo. I found a similar issue that might be helpful - https://github.com/kubernetes/ingress-nginx/issues/5996. 

There should be no restriction on the number of ingress controllers deployed on the cluster.

Is the CSI driver issue resolved now?

**Comment by kanukhosla** [comment] 2020-11-23 20:05
> Is the CSI driver issue resolved now?

Yes . thanks .
Let me try the link you shared

**Closed** 2020-11-23 21:20 UTC
Labels: bug
