### ISSUE TITLE
permissions required when using managed identity

### ISSUE THREAD

**Issue by ahmedsza** [Azure/secrets-store-csi-driver-provider-azure#227] opened 2020-09-09 13:49 UTC
**What steps did you take and what happened:**
I was getting this error- AKS cluster with managed identity
 
failed to apply binding api/azure-pod-identity-binding node aks-nodepool1-28849957-vmss000002 for pod api/trips-7cf9848d6-6qc7b, error: failed to update identities for aks-nodepool1-28849957-vmss in MC_teamResources_ahmsohex2_westeurope, error: compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client '98bb65c6-d885-44a7-88fd-1b60d8d5b5a6' with object id '98bb65c6-d885-44a7-88fd-1b60d8d5b5a6' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/4135126c-0362-4eb3-94f0-105cf7f8b9a9/resourceGroups/MC_teamResources_ahmsohex2_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-28849957-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/4135126c-0362-4eb3-94f0-105cf7f8b9a9/resourcegroups/teamresources/providers/microsoft.managedidentity/userassignedidentities/akspodidentity' or the linked scope(s) are invalid."

I then added a line similar to this 
az role assignment create --role "$clientId=( az aks show --name $aksname --resource-group $rgname --query identityProfile.kubeletidentity.clientId -o tsv)r" --assignee $clientId --scope /subscriptions/$subscriptionid/resourcegroups/$rgname
i,e where I have the AKS clientid access to "host RG" and then it worked

clientid is set as follows
$clientId=( az aks show --name $aksname --resource-group $rgname --query identityProfile.kubeletidentity.clientId -o tsv)

I already had this line which gave access to the noderesourcegroup
az role assignment create --role "Managed Identity Operator" --assignee $clientId --scope /subscriptions/$subscriptionid/resourcegroups/$nodeResourceGroup

Is this by design. Does the clientid for the aks cluster need to given Managed Identity Operator on both resource groups?

or is there something else I am not doing right. I have looked through the docs many times.

Side q: when do the MIC pods need to be killed?

**Comment by aramase** [comment] 2020-09-09 16:19
@ahmedsza The `Managed Identity Operator` role is required on the managed identity that `aad-pod-identity` needs to manage. The required role assignments are documented here - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md

**Comment by ahmedsza** [comment] 2020-09-09 18:00
Thanks @aramase . According to https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md it needs Managed Identity Operator permission to the MC_ group. I had that but it did not work. 
When I added an additional permission of Managed Identity Operator to the "AKS resource group" then it worked - and I am trying to understand if this is by design.  Both this doc and the official doc https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes#assign-your-service-principal-or-use-managed-identities indicate that  I just need the permission. So this is more a doc issue.  So my question is whether there is a permission that is not fully documented?

**Comment by aramase** [comment] 2020-09-09 18:03
@ahmedsza If the identities aren't in `MC_` resource group, then the `Managed Identity Operator` needs to be assigned for the resource group in which identities exist. This section of the doc calls that out: https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md#user-assigned-identities-that-are-not-within-the-cluster-resource-group. This is by design. Essentially `Managed Identity Operator` role is required for MIC to access the identity and assign it. So the permissions are required for the Identity resource group.

**Comment by aramase** [comment] 2020-09-09 18:04
@ahmedsza If the identities aren't in `MC_` resource group, then the `Managed Identity Operator` needs to be assigned for the resource group in which identities exist. This section of the doc calls that out: https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md#user-assigned-identities-that-are-not-within-the-cluster-resource-group. This is by design. Essentially `Managed Identity Operator` role is required for MIC to access the identity and assign it. So the permissions are required for the Identity resource group.

**Comment by ahmedsza** [comment] 2020-09-09 18:19
I did see that but thought it did not apply as this is a cluster managed identity. Later I do create  "az identity create" and that is in the aks rg (not mc_). Are you saying in this case I need to grant additional permissions? Or put the az identity in the mc_ rg? I am following https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes almost to the t.. but it is not explicit as to which resource group should be used when using "az identity create"

**Comment by aramase** [comment] 2020-09-09 18:31
@ahmedsza The docs team is working on updating https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes. Also, that doesn't cover all possible scenarios extensively. I would recommend following the role assignment doc in `aad-pod-identity` - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md

This details the authentication methods - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md#more-on-authentication-methods. For managed identity cluster, the cluster identity is used for authenticating with Azure, so the role assignments are required.

**Comment by aramase** [comment] 2020-09-11 19:37
@ahmedsza Is the issue resolved now?

**Comment by ahmedsza** [comment] 2020-09-16 13:00
Hi @aramase . Apologies on the delay. I did have it working. My confusion was around the clear documentation. Your notes above help - and the better news is that it appears that https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes has been updated to show the role assignment to both resource groups. 

Thanks for your help

**Comment by aramase** [comment] 2020-09-16 16:04
Glad it's working now. Closing this issue now. Please feel free to reopen if you have any other issues.

**Closed by aramase** 2020-09-16 16:04 UTC
Labels: bug

**Comment by ekhaydarov** [comment] 2021-03-18 18:40
your link is now a [role assignment doc in aad-pod-identity](https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md) is now a 404. 

this hidden role assignment  is a clear issue that needs to be addressed as its issue after issue on this repository and elsewhere

**Comment by aramase** [comment] 2021-03-18 18:45
@ekhaydarov The docs in pod identity have been moved to the docs site: https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/.

The pod identity section in the docs have a reference to the link: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/pod-identity-mode/#configure-aad-pod-identity-to-access-keyvault

Please let us know if any other update to the docs will make it easier for you to find the links.

**Comment by ekhaydarov** [comment] 2021-03-18 20:01
Thanks for quick response @aramase. i should really have my own issue for this but im pressed for time. is there an open slack group somewhere where questions can be asked about this?

a suggestion to improve the docs would be to give an example for [Reducing number of role assignments](https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/#reducing-number-of-role-assignments). In terraform when assigning the role through `azurerm_role_assignment` you need to pass in a `principal_id` which when looking at resource groups there is no valid principal id. Therefore, how does one even assign a whole resource group to a role?

Thanks

**Comment by aramase** [comment] 2021-03-19 16:25
For `azurerm_role_assignment`, the `principal_id` is of the identity that the cluster is using for access to Azure resources: https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/#obtaining-the-id-of-the-managed-identity--service-principal.

The scope for that role assignment would be the resource group that contains the identities.

**Comment by ekhaydarov** [comment] 2021-03-19 17:19
>  you could assign the Managed Identity Operator role to the resource group the managed identities belong to
so when you say `identity that the cluster` is using is that the same as the quoted docs above? ie you cannot assign the resource group itself as. Therefore the docs absolutely do not make that clear. 

In my case. If i make a user assigned managed identity in the same resource group, will it inherit the role from the identity that the cluster is using? I am assuming no? therefore there will be no savings on the quota? in any case I am confused and the docs are not making it clear for me
