### ISSUE TITLE
Azure Key Vault provider is crashing on GPU nodes

### ISSUE THREAD

**Issue by EppO** [Azure/secrets-store-csi-driver-provider-azure#544] opened 2021-06-16 14:53 UTC
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
When using a GPU nodepool with AKS, pod is crashing on the GPU nodes. On the CPU nodes, pod is running fine.

```
Warning  Failed     27m (x5 over 29m)      kubelet            Error: failed to create containerd task: OCI runtime create failed: container_linux.go:344: starting container process caused "chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied": unknown
```

```
csi-secrets-store-provider-azure-7pvhx                            0/1     CrashLoopBackOff   10         29m     10.x.x.x   aks-gpunodepool-x-vmss000000   <none>           <none>
csi-secrets-store-provider-azure-l6vb2                            1/1     Running            0          29m     10.x.x.x   aks-cpunodepool-x-vmss000000   <none>           <none>
csi-secrets-store-provider-azure-secrets-store-csi-driver-lgnww   3/3     Running            0          29m     10.x.x.x   aks-cpunodepool-x-vmss000000   <none>           <none>
csi-secrets-store-provider-azure-secrets-store-csi-driver-rph2j   3/3     Running            0          29m     10.x.x.x   aks-gpunodepool-x-vmss000000   <none>           <none>
```

**What did you expect to happen:**
Pod should be running correctly in any type of nodes.

**Anything else you would like to add:**
Rollback to 0.19.0 works just fine. I guess the issue is the cap drop and the GPU node in Azure:
```
          securityContext:
            runAsUser: 0
            capabilities:
              drop:
              - ALL
```

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 0.0.20
- Azure Key Vault provider version: (use the image tag): 0.0.23
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 
```
aks-cpunodepool-x-vmss000000   Ready    agent   6d17h   v1.20.7   10.x.x.x    <none>        Ubuntu 18.04.5 LTS   5.4.0-1047-azure   containerd://1.4.4+azure
aks-gpunodepool-x-vmss000000   Ready    agent   6d17h   v1.20.7   10.x.x.x    <none>        Ubuntu 18.04.5 LTS   5.4.0-1047-azure   containerd://1.4.4+azure
```
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by nilekhc** [comment] 2021-06-16 17:47
@EppO Thanks for reporting this. Could you also provide logs for failing provider pod?

**Comment by linearfunctional** [comment] 2021-07-13 05:10
I am facing the same issue. When can I expect it to be fixed?

**Comment by sozercan** [comment] 2021-07-15 23:45
@linearfunctional looks like this is related to a runc regression in rc93: https://danielmangum.com/posts/runc-chdir-to-cwd/ 
it's fixed in rc94: https://github.com/opencontainers/runc/pull/2894

Can you verify if you are running rc93 by running `runc --version` in your node? and can you upgrade your node pool, which should upgrade your runc version to rc95 or later and confirm if that fixes your issues?

**Closed** 2021-07-21 19:53 UTC
Labels: bug
