### ISSUE TITLE
Key Vault secret rotation does not update secret and pod mount

### ISSUE THREAD

**Issue by SoujanyaMangipudi** [Azure/secrets-store-csi-driver-provider-azure#872] opened 2022-04-29 21:27 UTC
AKS cluster with CSI add on key vault secret value auto rotation does not work. The value gets synced when pod is deployed for first time but subsequent updates are not reflected back on the cluster. 

csi driver pods have these errors

E0429 21:14:41.890342       1 reconciler.go:229] "failed to reconcile spc for pod" err="failed to get service account token attrs, err: failed to fetch token: serviceaccounts \"default\" is forbidden: User \"system:serviceaccount:kube-system:aks-secrets-store-csi-driver\" cannot create resource \"serviceaccounts/token\" in API group \"\" in the namespace \"ccp-geneva\"" spc="geneva-certificate-provider" pod="init-secrets-868d455dc6-4lzjr" controller="rotation"
E0429 21:14:51.897790       1 reconciler.go:229] "failed to reconcile spc for pod" err="failed to get service account token attrs, err: failed to fetch token: serviceaccounts \"default\" is forbidden: User \"system:serviceaccount:kube-system:aks-secrets-store-csi-driver\" cannot create resource \"serviceaccounts/token\" in API group \"\" in the namespace \"ccpgls\"" spc="gls-csi-provider" pod="glssecretsync-764b87f5b4-v7nnq" controller="rotation"
E0429 21:14:51.899404       1 reconciler.go:229] "failed to reconcile spc for pod" err="failed to get service account token attrs, err: failed to fetch token: serviceaccounts \"default\" is forbidden: User \"system:serviceaccount:kube-system:aks-secrets-store-csi-driver\" cannot create resource \"serviceaccounts/token\" in API group \"\" in the namespace \"istio-system\"" spc="istio-akv-csi-provider" pod="istio-secrets-syncer-7b96b96b77-9hvjv" controller="rotation"
E0429 21:14:51.900575       1 reconciler.go:229] "failed to reconcile spc for pod" err="failed to get service account token attrs, err: failed to fetch token: serviceaccounts \"default\" is forbidden: User \"system:serviceaccount:kube-system:aks-secrets-store-csi-driver\" cannot create resource \"serviceaccounts/token\" in API group \"\" in the namespace \"ccp-geneva\"" spc="geneva-certificate-provider" pod="init-secrets-868d455dc6-4lzjr" controller="rotation"

**What did you expect to happen:**
Secret should be updated back to the cluster.

**Anything else you would like to add:**
This cluster uses managed mode of CSI by enabling addon

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**
PROD

- Secrets Store CSI Driver version: csi-node-driver-registrar:v2.5.0
- Azure Key Vault provider version: (use the image tag): mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.1.0
- Kubernetes version: v1.22.6
- Cluster type: AKS

**Comment by nilekhc** [comment] 2022-04-29 22:09
Hi @SoujanyaMangipudi, Thanks for opening issue. Have you turned on `--enable-secret-rotation` flag while installing add-on?

https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#enable-and-disable-autorotation

**Comment by SoujanyaMangipudi** [comment] 2022-04-30 00:54
Yes @nilekhc following is a snapshot of one of the pods. 
![image](https://user-images.githubusercontent.com/19557867/166084214-4f644714-778c-4293-bf8d-f271521da3c3.png)

**Comment by aramase** [comment] 2022-05-02 13:54
@SoujanyaMangipudi If you're using the AKS add-on, please see https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/871 and the tagged issue for temporary resolution. The AKS team is rolling out the fix.

**Comment by aramase** [comment] 2022-05-02 15:30
From the logs `aks-secrets-store-csi-driver` it seems you're using the AKS add-on. I'll close this issue as duplicate of #871. Please use that issue to track the fix.

**Closed by aramase** 2022-05-02 15:30 UTC
Labels: bug
