### ISSUE TITLE
When using podIdentity mode and multiple pod identities  - enable to specify the clientid or resource id of the pod identity

### ISSUE THREAD

**Issue by vsabella** [Azure/secrets-store-csi-driver-provider-azure#377] opened 2021-01-22 02:37 UTC
**Describe the solution you'd like**
Not sure if this works with CSI Secrets Driver but - we want to mount multiple pod identities to a pod. It would be great if usePodIdentity could also take the clientid or resourceId and use it to select the right pod identity.

https://azure.github.io/aad-pod-identity/docs/best-practices/

**Environment:**
- Cluster type: AKS

**Comment by aramase** [comment] 2021-01-22 16:51
@vsabella Thank you for opening the issue.

This is duplicate of #284. Closing this issue so we can track this request there. Please feel free to reopen if you've any questions.

**Closed by aramase** 2021-01-22 16:51 UTC
Labels: enhancement
