### ISSUE TITLE
Mount Failed: rpc error: code = Unknown desc = mount failed: exit status 32

### ISSUE THREAD

**Issue by swapnilpotnis** [Azure/secrets-store-csi-driver-provider-azure#665] opened 2021-09-30 12:36 UTC
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Following the tutorial(https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/installation/#deployment-using-helm), I installed csi-driver in kube-system namespace using the following command:
`helm install csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --namespace kube-system`

**What did you expect to happen:**
Deployment.yaml for my microservice should mount the respective secrets and be consumed as environment variables

**What is actually happening:**
`  Warning  FailedMount  3s (x6 over 19s)  kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t tmpfs tmpfs /var/lib/kubelet/pods/<id>/volumes/kubernetes.io~csi/secrets-store-inline/mount
Output: mount: /var/lib/kubelet/pods/<id>/volumes/kubernetes.io~csi/secrets-store-inline/mount: mount point does not exist.`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
 User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): Default installed version
- Azure Key Vault provider version: (use the image tag): Default installed version
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
`kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-16T02:41:51Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"0b17c6315e806a66d507e77760a5d60ab5cccfd8", GitTreeState:"clean", BuildDate:"2021-08-30T01:42:22Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
`
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment] 2021-09-30 15:22
What version of the driver and provider are you installing? Could you share the command output for `helm ls -A`?

**Comment by swapnilpotnis** [comment] 2021-09-30 16:04
`csi             	kube-system	1       	2021-09-30 17:39:32.111226238 +0530 IST	deployed	csi-secrets-store-provider-azure-0.0.10	0.0.8    `

**Comment by aramase** [comment] 2021-09-30 16:16
@swapnilpotnis That's an unsupported release from 1yr back. There have been quite a few changes since then. Could you use the latest release?

**Comment by swapnilpotnis** [comment] 2021-09-30 17:25
@aramase : I just made use of the instructions as posted on the following page: https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/installation/#deployment-using-helm

Haven't made any specific changes to the helm installation.

**Comment by aramase** [comment] 2021-09-30 17:41
@swapnilpotnis your helm repo might be outdated. Run `helm repo update` to fetch the latest versions available.

**Comment by swapnilpotnis** [comment] 2021-09-30 18:15
Thanks alot @aramase  for helping me out with the issue. Repo Update -> Installation worked for me.

**Comment by aramase** [comment] 2021-10-01 00:09
Thanks for confirming. I'm going to close this as the issue is resolved. Please feel free to reopen if you have any other issues.

**Closed by aramase** 2021-10-01 00:09 UTC
Labels: bug
