### ISSUE TITLE
Volume not being mounted to pods

### ISSUE THREAD

**Issue by Dyllaann** [Azure/secrets-store-csi-driver-provider-azure#328] opened 2020-11-26 15:05 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I'm trying to deploy pods mounting Azure KeyVault secrets in an Azure AKS cluster. When developing the app on docker-desktop, everything was working fine. After deploying the secrets-store-csi-driver-provider-azure to my live production cluster, pods are no longer able to mount the csi-secrets volume from the driver.

As soon as pods try to mount a volume, the secrets store node registrar is informing `2020-11-26T14:51:53.862734037Z E1126 14:51:53.862480       1 connection.go:129] Lost connection to unix:///csi/csi.sock.` and the pod gets a restart.

When using the exact same values.yaml files for both my application and the Azure secrets store on docker-desktop under WSL2, the pods start up containing the secrets.

**What did you expect to happen:**
The volume would be mounted properly, without any `secrets-store-csi-driver-XYZ` restarts

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
https://gist.github.com/Dyllaann/61864f59f500fd1e2a5a7e046171ce93 gist files containing setup.
I was able to see the following CPU Throttling while this was happening, but even increasing the limits of the secrets-store to `1000m`, it was still throttling 100%.
![image](https://user-images.githubusercontent.com/7451618/100366312-fc8a7e00-3000-11eb-9b02-cc42cafc8ba3.png)

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Service Principal. Credentials are verified working by using local installation.

**Environment:**

**- Secrets Store CSI Driver version: (use the image tag):** `v0.0.16`
**- Azure Key Vault provider version: (use the image tag):** `0.0.9`
**- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): **
```Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2a313bf59aa0e1c98bbee2aea6ae727d3f6da6fd", GitTreeState:"clean", BuildDate:"2020-09-03T05:20:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}```
**- Cluster type: (e.g. AKS, aks-engine, etc):** AKS. Using a NodePool of `Standard_DS2_v2` instances

**Comment by aramase** [comment] 2020-11-30 17:27
@Dyllaann Could you provide the logs from `secrets-store`, `node-driver-registrar` and `liveness-probe` container for the pod during the time of error?

**Comment by Dyllaann** [comment] 2020-12-01 11:24
Sure thing!

I got a set of logs for when the pod is CrashLooping and the secrets store pod restarts [here](https://gist.github.com/Dyllaann/989b247af6dab67bca8761c8d2a4c1b6)
And also a set of logs when the secrets store already exists and then we install the pod [here](https://gist.github.com/Dyllaann/9aa50d99a3591cd6eb6ff0fd16468684)

Hope these help :)

**Comment by aramase** [comment] 2020-12-01 23:49
In the logs you posted, I don't see any errors and the logs show mount succeeded. However the `lost connection` is interesting. Is this happening only on a specific node? Is there anything interesting in the `kubelet` logs for the node?

**Comment by Dyllaann** [comment] 2020-12-08 15:35
I don't see anything that would raise a concern for me directly. There is something being logged quite frequently about orphaned pods and volumes being left over. I suspect this could be the CSI volume.
Full log during pod initialization [here](https://gist.github.com/Dyllaann/411f166050d7e67187cfafad4a54f722)

**Comment by aramase** [comment] 2020-12-09 18:47
@Dyllaann Have you tried with a different Kubernetes version? I can't reproduce this error. Does this only happen with a particular node in your cluster? Also, could you try the latest version of the driver and provider?

**Comment by Extant-1** [comment] 2020-12-09 23:58
@Dyllaann We were encountering the same error and pod crashing when trying to mirror a key vault secret. Turns out an egress TCP network policy was needed for the secrets-store-csi-driver pods.

**Comment by aramase** [comment] 2020-12-10 01:03
@Extant-1 Was this error in the provider pod when trying to fetch the secret content from Key Vault? Could you post the sample policy that you applied here?

**Comment by Extant-1** [comment] 2020-12-10 04:20
Note this did fix the issue for some of our clusters but we are still noticing OOMemory crashes in some of them. Only happens when the driver attempts to create the secret specified in the SecretProviderClass:

```
Name:         key-vault-csi-driver
Namespace:    key-vault-csi
API Version:  crd.projectcalico.org/v1
Kind:         NetworkPolicy
Spec:
  Egress:
    Action:    Allow
    Protocol:  TCP
  Selector:    app == 'secrets-store-csi-driver'
  Types:
    Egress

**Comment by aramase** [comment] 2020-12-10 07:39
@Extant-1 What is the kubernetes version? Do you have the logs from the driver pods before restart?

**Comment by Extant-1** [comment] 2020-12-10 23:40
Hey @aramase 

1. 1.18.8
2. See my previous post, those were the last logs before the crash and restart
3. I increased the resource limit to 400m / 400Mi for the driver container which seems to have stabilized it.
4. No
5. Two. only one of which is using the secret syncing, the other is not and has not had any issues.
6. Yes I did see OOMKilled. After the secret was mounted though, it seemed to recover and stabilize.
![image](https://user-images.githubusercontent.com/28478122/101842796-efdb5d80-3b9c-11eb-9688-9b02eb2e1a45.png)

**Comment by aramase** [comment] 2020-12-11 22:42
That's interesting. I've a soak cluster with the same kubernetes version which has been around for 10 days now which has the CSI driver and provider deployed. I'm using the secret rotation feature as well with 2 `SecretProviderClass` and don't see any spike in CPU or memory.

**Comment by Dyllaann** [comment] 2020-12-15 10:28
> @Dyllaann Have you tried with a different Kubernetes version? I can't reproduce this error. Does this only happen with a particular node in your cluster? Also, could you try the latest version of the driver and provider?

@aramase I haven't tried a new Kubernetes version yet, since the issue involves a production cluster. Regardless, it happens for pods deployed to any node.
I did just update the driver to the latest version, so any findings now will be on latest version.

For the sake of debugging step-by-step, I've disabled the secret mirroring for now, and that actually made the volume mount work without any problem.
So, that changes the scope from volume mounting to secret object mirroring. 
If i re-enable the `secretObjects` section in my SecretProviderClass, pods are unable to start up again with the following error:
```MountVolume.SetUp failed for volume "vault-secrets" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake```

I can now also seen an error in the secrets-store container that is from the keyvault pod on the same node:
```reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1.Secret: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 205; INTERNAL_ERROR```
Not long after this error, the keyvault driver will also get the `Lost connection to unix:///csi/csi.sock.` and restart

**Comment by aramase** [comment] 2020-12-15 17:11
@Dyllaann Thank you for investigating more. That looks like an error from the API server while trying to fetch secrets. How many Kubernetes secrets do you have in your cluster across all namespaces?

**Comment by Dyllaann** [comment] 2020-12-15 18:53
The complete sum of secrets in my cluster is `3731`. I expected a lot less, but forgot all Helm3 releases are now stored as a secret.
Nonetheless, is that such an excessive amount the API server isn't able to handle it?

**Comment by aramase** [comment] 2020-12-15 19:09
The default timeout for the API server request is `60s`. But from the logs you posted, it looks the API server is unable to serve the request within the specified timeout. The `controller-runtime` library the CSI driver uses is performing chunking and only requesting for `500` secrets (`apiserver panic'd on GET /api/v1/secrets?limit=500&resourceVersion=0\n`) but the API server still seems to be unable to respond. How responsive is `kubectl get secrets -A` command?

**Comment by Dyllaann** [comment] 2020-12-15 19:20
I guess 1 second for all 3731 secrets is fine if the timeout is 60s 
````
~ echo "`date +%H:%M:%S:%3N`"&& kubectl get secrets -A &>/dev/null && echo "`date +%H:%M:%S:%3N`"
20:17:25:123
20:17:26:187
```

Repeating the above command a couple times, I'd say one second is pretty average. Maximum time it took for the request to complete was 1,5 second.

**Comment by aramase** [comment] 2020-12-15 19:47
I just created 3500 secrets in my cluster to test:

```
~ at ☸️  v1.16.15 c00
➜ kubectl get secrets | wc -l
    3508

~ at ☸️  v1.16.15 c00
➜ kubectl top pods
NAME                                         CPU(cores)   MEMORY(bytes)
csi-csi-secrets-store-provider-azure-nvf2x   3m           14Mi
csi-secrets-store-csi-driver-24gnf           4m           44Mi
```

The driver pods are still up and running. I also have the secrets auto rotation feature enabled. Could you increase the cpu and memory limits on the `secrets-store` container for the driver pods?

**Comment by Dyllaann** [comment] 2020-12-15 20:01
Have you deployed an application that triggers the secret retrieval too? Idling works fine for me too (even under default limits).
Its only when you deploy a pod that uses a secretproviderclass, mount and secret mirroring when things start to fail.
I will test some scenarios with increased pod limits and come back on that.

**Comment by aramase** [comment] 2020-12-15 20:16
Yeah, I've 2 `SecretProviderClass` with `secretObjects` and 4 application pods.

**Comment by Dyllaann** [comment] 2020-12-16 12:17
Alright, I've done some testing with increasing the limits of the `secrets-store` specific. I increased the cpu limit to `1` and the memory limit to `512Mi`.
Unfortunately, still experiencing the same problem. 

secrets-store logs:
```
I1216 12:10:02.320374       1 nodeserver.go:208] "node publish volume complete" targetPath="/var/lib/kubelet/pods/d2318ef8-3146-4abd-90e6-524fe98db9b4/volumes/kubernetes.io~csi/vault-secrets/mount" pod="mynamespace/api-84d9d69999-n55z2"

I1216 12:11:16.438023       1 trace.go:205] Trace[1106410694]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156 (16-Dec-2020 12:10:02.722) (total time: 73715ms):Trace[1106410694]: [1m13.715222033s] [1m13.715222033s] END

E1216 12:11:16.438051       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1.Secret: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 199; INTERNAL_ERROR
```
I guess the problem still remains on the kubeapi side :(.

**Comment by Dyllaann** [comment] 2020-12-16 12:27
Alright, I've increased the limits on the `secret-store` specifically, and it looks like the first success. My secret object is created now and application is able to start up.
The set up limits with which this was achieved were
```
secrets-store-csi-driver:
  linux:
    driver:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 1
          memory: 512Mi
```

When doing a second try, it failed again.

```
I1216 12:19:50.198612       1 nodeserver.go:208] "node publish volume complete" targetPath="/var/lib/kubelet/pods/db0f78ba-4f98-444c-9fc7-402d5410ca86/volumes/kubernetes.io~csi/vault-secrets/mount" pod="qa-jedlix-catalog/api-84d9d69999-zjs5c"
I1216 12:22:05.807372       1 trace.go:205] Trace[336122540]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156 (16-Dec-2020 12:19:50.800) (total time: 135007ms):Trace[336122540]: [2m15.007055638s] [2m15.007055638s] END
E1216 12:22:05.807406       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1.Secret: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 193; INTERNAL_ERROR
```

So I'm not sure whether the one-time success was due to the limits being increased, or because the kubeapi didn't panic for once.
Worthy sidenote: there are still multiple  `Lost connection to unix:///csi/csi.sock.` and `secrets-store-csi-driver-xyz` pod restarts happening.

Besides that, I can't imagine a limit of `1` is a preffered limit for production usage ;)

**Comment by Dyllaann** [comment] 2020-12-16 12:27
Alright, I've increased the limits on the `secret-store` specifically, and it looks like the first success. My secret object is created now and application is able to start up.
The set up limits with which this was achieved were
```
secrets-store-csi-driver:
  linux:
    driver:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 1
          memory: 512Mi
```

When doing a second, third and fourth try, it failed again.

```
I1216 12:19:50.198612       1 nodeserver.go:208] "node publish volume complete" targetPath="/var/lib/kubelet/pods/db0f78ba-4f98-444c-9fc7-402d5410ca86/volumes/kubernetes.io~csi/vault-secrets/mount" pod="mynamespace/api-84d9d69999-zjs5c"
I1216 12:22:05.807372       1 trace.go:205] Trace[336122540]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156 (16-Dec-2020 12:19:50.800) (total time: 135007ms):Trace[336122540]: [2m15.007055638s] [2m15.007055638s] END
E1216 12:22:05.807406       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1.Secret: failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 193; INTERNAL_ERROR
```

So I'm not sure whether the one-time success was due to the limits being increased, or because the kubeapi didn't panic for once.
Worthy sidenote: there are still multiple  `Lost connection to unix:///csi/csi.sock.` and `secrets-store-csi-driver-xyz` pod restarts happening.

Besides that, I can't imagine a limit of `1` is a preffered limit for production usage ;)

**Comment by aramase** [comment] 2020-12-16 17:09
@Dyllaann What is the memory and cpu consumption for the CSI driver pod now?

**Comment by Dyllaann** [comment] 2020-12-18 13:57
![image](https://user-images.githubusercontent.com/7451618/102622312-1f600c00-4141-11eb-9dfd-c7791ee46141.png)
![image](https://user-images.githubusercontent.com/7451618/102622336-25ee8380-4141-11eb-881c-bd4b933e5c97.png)

**Comment by sandermvanvliet** [comment] 2020-12-23 08:14
@aramase colleague of @Dyllaann here, we now have 2 out of 10 nodes having issues with the csi driver pod.
When I log onto the nodes in question and run a `dmesg` I can see the following:

```
[4190858.009189] Task in /kubepods/burstable/pod613c1744-2bcb-42cb-a8ac-a33b0dbea2b6/4fc25b03907e75c884c376b7fb27f1e8261dfcb5c86eb267a3164dd618011e87 killed as a result of limit of /kubepods/burstable/pod613c1744-2bcb-42cb-a8ac-a33b0dbea2b6/4fc25b03907e75c884c376b7fb27f1e8261dfcb5c86eb267a3164dd618011e87
[4190858.009193] memory: usage 204800kB, limit 204800kB, failcnt 35
[4190858.009194] memory+swap: usage 0kB, limit 9007199254740988kB, failcnt 0
[4190858.009195] kmem: usage 1912kB, limit 9007199254740988kB, failcnt 0
[4190858.009195] Memory cgroup stats for /kubepods/burstable/pod613c1744-2bcb-42cb-a8ac-a33b0dbea2b6/4fc25b03907e75c884c376b7fb27f1e8261dfcb5c86eb267a3164dd618011e87: cache:0KB rss:202888KB rss_huge:172032KB shmem:0KB mapped_file:0KB dirty:0KB writeback:0KB inactive_anon:0KB active_anon:202844KB inactive
[4190858.009201] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[4190858.009396] [19679]     0 19679   102563    56481   552960        0           972 secrets-store-c
[4190858.009403] Memory cgroup out of memory: Kill process 19679 (secrets-store-c) score 2040 or sacrifice child
[4190858.194054] Killed process 19679 (secrets-store-c) total-vm:410252kB, anon-rss:202084kB, file-rss:23840kB, shmem-rss:0kB
[4190860.003893] oom_reaper: reaped process 19679 (secrets-store-c), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

which does suggest high memory pressure on these pods.
After increasing the limit and after all pods are rescheduled I see 2 of 10 pods having issues (on different nodes though).
What's interesting is that when you look at the resource consumption you can see the memory usage goes up fairly rapidly towards the limit:

![image](https://user-images.githubusercontent.com/2393265/102974297-965d2200-44fe-11eb-8c24-60dd85f99336.png)]

and shortly after blowing completely past that:

![image](https://user-images.githubusercontent.com/2393265/102974366-affe6980-44fe-11eb-8c0a-6d1474c6cbd8.png)

And after that it gets OOMKilled:

```
[3598313.323339] secrets-store-c invoked oom-killer: gfp_mask=0x14000c0(GFP_KERNEL), nodemask=(null), order=0, oom_score_adj=972
[3598313.323341] secrets-store-c cpuset=87ecf53d899af8ba9e0964296833092aefd2ad24a434820929610310b146be3e mems_allowed=0
[3598313.323354] CPU: 1 PID: 7704 Comm: secrets-store-c Tainted: G        W        4.15.0-1098-azure #109~16.04.1-Ubuntu
[3598313.323355] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS 090008  12/07/2018
[3598313.323356] Call Trace:
[3598313.323367]  dump_stack+0x6d/0x92
[3598313.323373]  dump_header+0x77/0x285
[3598313.323376]  oom_kill_process+0x22d/0x430
[3598313.323378]  out_of_memory+0x11d/0x4c0
[3598313.323384]  mem_cgroup_out_of_memory+0xb9/0xd0
[3598313.323387]  mem_cgroup_oom_synchronize+0x32a/0x350
[3598313.323389]  ? mem_cgroup_css_reset+0xe0/0xe0
[3598313.323391]  pagefault_out_of_memory+0x36/0x7b
[3598313.323397]  mm_fault_error+0x8f/0x190
[3598313.323401]  ? handle_mm_fault+0xcc/0x1f0
[3598313.323403]  __do_page_fault+0x480/0x4d0
[3598313.323405]  do_page_fault+0x38/0x130
[3598313.323409]  ? page_fault+0x2f/0x50
[3598313.323410]  page_fault+0x45/0x50
[3598313.323412] RIP: 0033:0x4604d8
[3598313.323413] RSP: 002b:000000c001134f70 EFLAGS: 00010202
[3598313.323415] RAX: 0000000000000080 RBX: 000000000001bfe0 RCX: 000000c011f37000
[3598313.323415] RDX: 000000c011eba000 RSI: 000000c011f1b020 RDI: 000000c012d7afa0
[3598313.323416] RBP: 000000c001134fc8 R08: 0000000000000640 R09: 000000c011eba000
[3598313.323417] R10: 000000c012d1a000 R11: 0000000000000020 R12: 0000000000000002
[3598313.323418] R13: 00000000026f4000 R14: 000000000045eef0 R15: 0000000000000000
[3598313.323419] Task in /kubepods/burstable/pod166d11bf-2c22-4675-9f1b-17c850c87faf/87ecf53d899af8ba9e0964296833092aefd2ad24a434820929610310b146be3e killed as a result of limit of /kubepods/burstable/pod166d11bf-2c22-4675-9f1b-17c850c87faf/87ecf53d899af8ba9e0964296833092aefd2ad24a434820929610310b146be3e
[3598313.323423] memory: usage 262144kB, limit 262144kB, failcnt 909
[3598313.323424] memory+swap: usage 0kB, limit 9007199254740988kB, failcnt 0
[3598313.323425] kmem: usage 1520kB, limit 9007199254740988kB, failcnt 0
[3598313.323425] Memory cgroup stats for /kubepods/burstable/pod166d11bf-2c22-4675-9f1b-17c850c87faf/87ecf53d899af8ba9e0964296833092aefd2ad24a434820929610310b146be3e: cache:0KB rss:260624KB rss_huge:165888KB shmem:0KB mapped_file:0KB dirty:0KB writeback:0KB inactive_anon:0KB active_anon:260624KB inactive
_file:0KB active_file:0KB unevictable:0KB
[3598313.323433] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[3598313.323721] [ 7663]     0  7663   102579    68394   647168        0           972 secrets-store-c
[3598313.323724] Memory cgroup out of memory: Kill process 7663 (secrets-store-c) score 1978 or sacrifice child
[3598313.622417] Killed process 7663 (secrets-store-c) total-vm:410316kB, anon-rss:260196kB, file-rss:13380kB, shmem-rss:0kB
[3598318.107365] oom_reaper: reaped process 7663 (secrets-store-c), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

I don't have a lot of additional leads yet but I think the interesting fact is that it always happens to 2 out of 10 nodes and that it's not specific to any node.

Hope this might give some additional clues.

**Comment by sandermvanvliet** [comment] 2020-12-23 08:48
All right, I might have thrown a red-herring here.
The 2 nodes affected are the nodes where the test application we use for this is scheduled on, that app has 2 replicas so that explains why we only see this on 2 of the 10 nodes.

**Comment by aramase** [comment] 2021-04-05 22:49
We've made a number of optimizations based on load testing in our latest releases. Please checkout:

https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.21
https://secrets-store-csi-driver.sigs.k8s.io/load-tests.html
https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/0.0.14

Try it out when you get a chance and let us know if the issue still persists.

**Comment by aramase** [comment] 2021-04-26 17:59
Closing this issue with the latest releases that have load test optimizations. Please feel free to open a new issue if you have any questions.

**Closed by aramase** 2021-04-26 17:59 UTC
Labels: bug
