### ISSUE TITLE
Secret Provider Class not support secretObject type stringData

### ISSUE THREAD

**Issue by tamanh123456** [Azure/secrets-store-csi-driver-provider-azure#863] opened 2022-04-20 07:16 UTC
**Describe the solution you'd like**
I deploy Drupal on Azure Kubernetes Service and mount key vault (key vault store database configuration). And drupal source has a option to get environment variables by .env file.
But csi mount secret not like my expect

**Anything else you would like to add:**
I expect the Secretproviderclass has more option to create secret like stringData type

**k8s secret I expect secretproviderclass will create**
```
kind: Secret
apiVersion: v1
metadata:
  name: environment-secret
type: Opaque
stringData:
  .env: |-
    db_host=my-db.host
    db_user=db-user
    db_password=db-pass
```
**secretproviderclass config I expect**
```
secretObjects:
- secretName: environment-secret
  type: Opaque
  stringData:
    .env: |-
      db_host=my-db.host
      db_user=db-user
      db_password=db-pass
```
**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.0.1
- Kubernetes version: (use `kubectl version`): v1.21.9
- Cluster type: AKS

**Comment by aramase** [comment] 2022-04-20 13:57
Duplicate of https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/937. This is a driver feature request, so closing this issue.

**Closed by aramase** 2022-04-20 13:57 UTC
Labels: enhancement
