### ISSUE TITLE
Support synchronization to secrets without a pod mount

### ISSUE THREAD

**Issue by lpghartz** [Azure/secrets-store-csi-driver-provider-azure#320] opened 2020-11-18 13:59 UTC
**Describe the solution you'd like**

Currently the driver will only sync secrets into a Kubenetes secret if they are mounted onto a pod. This makes it impossible to use KeyVault secrets with services that do not mount secrets, but rather access them via API, without using a hacky work-around like starting a temporary pod with the secret mounted so it triggers the secret to be created. 

Some services (in our case, cert-manager) do not mount secrets to pods if they are configured with a secret (such as providing API authentication to the DNS01 resolvers). 

There are a good number of Kubernetes services that work with secrets this way, so this causes a need to manage secrets via two methods.

**Comment by aramase** [comment] 2020-11-18 23:59
This is a duplicate of https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/298. Please feel free to add your thoughts to that issue.

**Closed by aramase** 2020-11-18 23:59 UTC
Labels: enhancement
