### ISSUE TITLE
kubernetes secret sync without creating pod

### ISSUE THREAD

**Issue by aelmanaa** [Azure/secrets-store-csi-driver-provider-azure#271] opened 2020-10-14 12:20 UTC
**Describe the solution you'd like**
Hello,

currently we have to create a secret provider class and a pod so that a k8s object gets created
would it be possible to have a controller which sync automatically azure keyvault with k8s secrets without going through the pod creation step?

the current solution works fine so this is suggestion is a nice to have feature (if possible of course)

**Comment by aramase** [comment] 2020-10-14 21:11
Duplicate of https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/298

I've added few comments in the issue. Please feel free to chime in there.

**Closed by aramase** 2020-10-14 21:11 UTC
Labels: enhancement
