### ISSUE TITLE
enable pod identity through annotations

### ISSUE THREAD

**Issue by ekhaydarov** [Azure/secrets-store-csi-driver-provider-azure#399] opened 2021-02-12 12:06 UTC
Looking through [this](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/pod-identity-mode/) documentation we can see that the way to make pod identity work is to add a label on the pod spec that will be performing the access. It all works which is great.

However, the standard seems to be to use pod annotations to create markers like this in pretty much every open source k8s application I have used. Thats why in a helm chart there is always a default `podAnnotation: {}` for users to be able to annotate their pods. Its no big deal to use labels but I think for ease of use for the wider community it would be great to support the annotation instead of the label

Thanks

**Comment by aramase** [comment] 2021-02-17 18:45
Closing this as duplicate of https://github.com/Azure/aad-pod-identity/issues/302

**Closed by aramase** 2021-02-17 18:45 UTC
