### ISSUE TITLE
Fail to integrate key vault with AKS cluster

### ISSUE THREAD

**Issue by xiaowanzizuibang** [Azure/secrets-store-csi-driver-provider-azure#348] opened 2020-12-22 05:41 UTC
![image](https://user-images.githubusercontent.com/45681473/102853221-dff43100-445a-11eb-95cf-447842a1b75b.png)
we deploy the environment via the document: 
https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes
But the pod is always in creating status and there is an error when describing the pod.
App pod and CSI secret provider are in same namespace.

**Comment by jai2shukla** [comment] 2020-12-22 06:36
Some more inputs on the issue is given below
SecretProviderClass:
![ServiceProvider](https://user-images.githubusercontent.com/10209268/102857055-c1d40400-444d-11eb-998c-6e9118b37976.JPG)

Pod file:
![pod](https://user-images.githubusercontent.com/10209268/102857096-d44e3d80-444d-11eb-8583-37e4d47c84f3.JPG)

**Comment by ritazh** [comment] 2020-12-22 19:03
Thanks for reporting the issue. Can you please help provide the following information:
```
**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
- Cluster type: (e.g. AKS, aks-engine, etc):
```

If you can also provide logs to the azure key vault provider pod, that would be helpful as well:
https://github.com/Azure/secrets-store-csi-driver-provider-azure#troubleshooting

**Comment by jai2shukla** [comment] 2020-12-23 05:44
CSI Driver version=0.0.18
Kubernetes version=1.18.10
Cluster Info: Load balancer type-**Public** and SKU- **basic**
![image](https://user-images.githubusercontent.com/10209268/102963379-ef34b680-450e-11eb-99cd-d86c2312cc48.png)
![image](https://user-images.githubusercontent.com/10209268/102963514-50f52080-450f-11eb-95cc-ef58014be455.png)
![image](https://user-images.githubusercontent.com/10209268/102963660-b0533080-450f-11eb-89cb-e286dfdb9d6b.png)

Please let me know if any other info is required

**Comment by ritazh** [comment] 2020-12-23 18:36
Thanks for the additional info @jai2shukla. 
From the secrets store csi driver log, it looks like it's defaulting to `GRPC supported provider: gcp`. It should say `GRPC supported provider: azure` to support the azure grpc provider.

If you use helm to install https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#installing-the-chart, `grpcSupportedProviders: azure` are already set in the values.yaml.  

If you are installing via individual yamls, https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/install-yamls.md#install-the-secrets-store-csi-driver, please add the `--grpc-supported-providers=azure` flag to the secrets-store container args.
> NOTE: 0.0.9+ release of the Azure Key Vault provider is incompatible with the Secrets Store CSI Driver versions < v0.0.14. While installing the Secrets Store CSI Driver using yamls, add the following flag --grpc-supported-providers=azure to the Linux and Windows daemonset manifests.

**Comment by jai2shukla** [comment] 2020-12-24 13:45
Removed everything and re-configured as per suggestion but issue still exist

![image](https://user-images.githubusercontent.com/10209268/103092029-fbf30080-461b-11eb-8d0e-f5674d1ee60e.png)
![image](https://user-images.githubusercontent.com/10209268/103092104-2d6bcc00-461c-11eb-84df-929575bc4f04.png)

**Comment by aramase** [comment] 2020-12-25 19:47
@jai2shukla How are you installing the driver and provider? From the snapshot it looks like there are only driver pods running on the node? If you install with the helm charts from this [repo](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure), then the driver and provider will be installed. If you're manually installing using yamls, then please make sure to add `--grpc-supported-providers=azure` to the driver yaml as documented [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/install-yamls.md).

Please follow the steps here for how to install the driver **and** provider pods: https://github.com/Azure/secrets-store-csi-driver-provider-azure#install-the-secrets-store-csi-driver-and-the-azure-keyvault-provider

Steps to do after deploy:
1. Confirm the driver pods are running. Describe the pods to check `--grpc-supported-providers=azure` is set as an arg for the `secrets-store` container. Also, you can confirm by looking at the logs: `kubectl logs <driver pod> -c secrets-store`. 
2. Confirm the driver pod is running on each node.
3. Then deploy your application pod
4. If there are errors, then check the logs from the driver and provider pods on the same node as your application.

**Comment by jai2shukla** [comment] 2020-12-26 01:13
Thanks it is working

**Comment by aramase** [comment] 2021-01-04 16:59
Thank you for confirming. Closing this as the issue is resolved now.

**Closed by aramase** 2021-01-04 16:59 UTC
