### ISSUE TITLE
Errors when updating to 1.1.3

### ISSUE THREAD

**Issue by vittoriocanilli** [Azure/secrets-store-csi-driver-provider-azure#892] opened 2022-05-18 09:33 UTC
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I have updated from version 1.1.2 to version 1.1.3 and that could not proceed because of this error:
```
ts=2022-05-18T08:35:28.734004285Z caller=release.go:357 component=release release=csi-secrets-store-provider-azure targetNamespace=kube-infrastructure resource=kube-infrastructure:helmrelease/csi-secrets-store-provider-azure helmVersion=v3 error="upgrade failed: template: csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml:25:18: executing \"csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml\" at <.Values.arc.enableMonitoring>: nil pointer evaluating interface {}.enableMonitoring" action=upgrade
```
I had to add this dummy attribute in my `values.yaml` file:
```
arc: {}
```
After that I have tried to update again, I got this other error message.
```
ts=2022-05-18T08:54:15.494870292Z caller=release.go:357 component=release release=csi-secrets-store-provider-azure targetNamespace=kube-infrastructure resource=kube-infrastructure:helmrelease/csi-secrets-store-provider-azure helmVersion=v3 error="upgrade failed: template: csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml:30:18: executing \"csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml\" at <.Values.Azure.proxySettings.isProxyEnabled>: nil pointer evaluating interface {}.proxySettings" action=upgrade
```
As workaround I had to add this attribute in my `values.yaml` file:
```
Azure:
  proxySettings:
    isProxyEnabled: false
```
Eventually I managed to update to version 1.1.3, but I had to add the 2 fore mentioned dummy attributes.

**What did you expect to happen:**
The 2 dummy attributes should not be necessary, as I am not using the new ARC monitoring, i.e. I  don't overwrite the default `
enableArcExtension: false` value.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Pod Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.1.3
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.22.6
- Cluster type: (e.g. AKS, aks-engine, etc):  AKS

**Comment by nilekhc** [comment] 2022-05-18 21:36
Hi @vittoriocanilli, Thanks for reporting issue. I have opened a PR to fix this. Feel free to add review. Once merged, this fix will be available in the next release.

**Comment by vittoriocanilli** [comment] 2022-05-19 08:50
Hi @nilekhc,

thanks for taking care of the issue so quickly. I will definitely have a look at the PR.

When I have opened this issue, I have noticed that the [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/) link is returning a 404. I am not sure if you can solve that, but I just wanted to point it out 😄

**Comment by aramase** [comment] 2022-05-19 15:16
Thanks for reporting the 404 issue. The docs are available here: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/. We'll update the issue template.

**Closed** 2022-05-20 23:54 UTC
Labels: bug

**Comment by danbrad** [comment] 2022-09-14 16:50
The PR attached to this doesn't  appear to have fixed the issue.

The problem is that the check is an AND, so if `enableArcExtension` is false, the check for `.Values.arc.enableMonitoring` and `.Values.Azure.proxySettings.isProxyEnabled` will also happen.

I've worked around by adding the dummy values, but I believe this shouldn't be necessary

**Comment by danbrad** [comment] 2022-09-14 16:57
Actually, I don't understand why it evaluates both sides of the and in this case, but it does as my upgrade to 1.3.0 definitely failed and the fix was to do as per this issue
