### ISSUE TITLE
csi-secrets-store-provider pods in Azure are reported as being privileged containers?

### ISSUE THREAD

**Issue by bhaugen-abledocs** [Azure/secrets-store-csi-driver-provider-azure#327] opened 2020-11-24 18:10 UTC
**What steps did you take and what happened:**
- Deployed the secrets-store-csi-drive-provider-azure via Helm
- Turned on Azure Defender
- Noticed that Azure now complains that the csi-secrets-store-provider pods are listed as affected components in the `Privileged containers should be avoid` security recommendation

**What did you expect to happen:**
- csi-secrets-store-provider pods would not be listed in an Azure Defender security recommendations

**Anything else you would like to add:**
I hope this is the right place to report this? Apologies if this is in the incorrect place and this is really an Azure Defender (or other Azure resource issue) or just a misconfiguration on my part.

Here is a screenshot of what I am seeing in Azure.
![Screen Shot 2020-11-24 at 11 56 57 AM](https://user-images.githubusercontent.com/68245042/100133700-b8567c80-2e4c-11eb-8b7c-3047d9581df1.png)

**Which access mode did you use to access the Azure Key Vault instance:**
- User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): csi-secrets-store-provider-azure-0.0.14
- Azure Key Vault provider version: (use the image tag): Not sure where to get this?
- Kubernetes version: 1.19.0
- Cluster type: AKS

**Comment by aramase** [comment] 2020-11-24 18:34
@bhaugen-abledocs The helm charts install 2 components - [Secrets Store CSI Driver](https://github.com/kubernetes-sigs/secrets-store-csi-drive) and the [AKV provider for Secrets Store CSI Driver](https://github.com/Azure/secrets-store-csi-driver-provider-azure). The CSI driver pods need to run in privileged mode to be able to mount volumes for the pod.

**Comment by bhaugen-abledocs** [comment] 2020-11-24 18:42
@aramase, okay so sounds like this is by design/required to make things functional with no workaround then? If that is the case then this issue can be closed I believe. Thanks for the quick response!

**Comment by aramase** [comment] 2020-11-24 19:28
@bhaugen-abledocs Can you try deploying in `kube-system` namespace. I just checked with @miwithro and he said the alert should be mitigated. The CSI driver pods are critical add-on pods which have high privileges. So `kube-system` would be the right fit for it.

**Comment by bhaugen-abledocs** [comment] 2020-11-24 19:32
> @bhaugen-abledocs Could you try deploying in `kube-system` namespace. I just checked with @miwithro and he said the alert should be mitigated for pods in `kube-system`. The CSI driver pods are critical add-on pods which have high privileges. So `kube-system` would be the right fit for it.

Ah, interesting. Yes, I can try that though may not get to it today (tomorrow for sure though).

**Comment by bhaugen-abledocs** [comment] 2020-11-25 19:43
@aramase, deploying into the `kube-system` namespace seems to have resolved the issue though I am not entirely sure Azure Defender has refreshed its data yet. Do you mind if we leave this open until Monday so I can make sure there has been enough time for Azure Defender to check everything again?

(I will also check in on it between here and Monday but since its Thanksgiving week for those in the US, I don't expect any responses until Monday at the earliest.)

**Comment by miwithro** [comment] 2020-11-25 19:47
@bhaugen-abledocs thanks for the follow up.  Standing by.

**Comment by aramase** [comment] 2020-11-30 18:41
@bhaugen-abledocs Thank you for following up. Do you still see the alert in Azure Defender?

**Comment by bhaugen-abledocs** [comment] 2020-12-01 16:41
@aramase, I no longer see the alert in Azure Defender! Sorry for the delay, I ran into issues getting things configured yesterday that were my own doing (if only I could spell and name things consistently 🤣).

I believe this issue can be closed/resolved now! Thanks 💯 for the help!

**Comment by aramase** [comment] 2020-12-01 17:11
@bhaugen-abledocs Glad the issue is resolved now. 

Closing this now. Please feel free to re-open if you've any questions.

**Closed by aramase** 2020-12-01 17:11 UTC
Labels: bug
