### ISSUE TITLE
How to create secret of type kubernetes.io/tls? Please add example for sync secrets of type kubernetes.io/tls with certificate type required.

### ISSUE THREAD

**Issue by sainipankaj90k** [Azure/secrets-store-csi-driver-provider-azure#104] opened 2020-05-19 02:59 UTC
First of all thanks for this project, I was looking for this exact scenario for my service.

I just followed the guidelines mentioned above and everything works as expected. 
Also, the section '[OPTIONAL] Sync with Kubernetes Secrets' works as expected for type 'Opaque'. **But, 'Sync with Kubernetes Secrets'' is not working for secret type 'kubernetes.io/tls'.**

Refer config below '**SecretProviderClass.yaml**'.
- secret1-k8 was created successfully in k8s' secrets.
- cert1pfx-k8 and cert1pem-k8 were not created in k8s' secrets. 

Here is the error message from the Pod: 
_Warning message: 'FailedMount' : MountVolume.SetUp failed for volume "secrets-store-volume-name" : **kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = tls key is not supported. Only tls.key and tls.crt are supported**_

Really appreciate your help. :)

# SecretProviderClass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "kvname"          # the name of the KeyVault
    cloudName: ""          # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: cert1pfx      #PFX type secret in KeyVault
          objectType: cert
          objectVersion: ""
        - |
          objectName: cert1pem     #PEM type secret in KeyVault
          objectType: cert
          objectVersion: ""
    resourceGroup: "testrg"               # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"            # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"                    # the tenant ID of the KeyVault                             
  secretObjects:                            
  - secretName: secret1-k8
    type: Opaque
    data:
    - objectName: secret1
      key: secret
  - secretName: cert1pfx-k8
    type: kubernetes.io/tls
    data:
    - objectName: cert1pfx
      key: secret
  - secretName: cert1pem-k8
    type: kubernetes.io/tls
    data:
    - objectName: cert1pem
      key: secret

**Comment by aramase** [comment] 2020-05-19 16:21
@sainipankaj90k The `secretObjects[*].key` needs to be `tls.key` and `tls.secret` for secret of type `kubernetes.io/tls`. Check out this example - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/sample/ingress-controller-tls/secretproviderclass-azure-tls.yaml

**Comment by sainipankaj90k** [comment] 2020-05-19 21:14
Thanks a lot, Anish Ramasekar.
This was helpful. **It worked for PEM type cert. Though it didn't work for pfx cert.**

We are using a pfx cert. For this one 'kubernetes.io/tls' is created but crt is empty. Is there a way to do it for pfx cert also?

Below is the output of get and describe command for secret:

**get secret:**
_data:
  tls.crt: ""
  tls.key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=_

**describe secret:**
_Data:
tls.crt:  0 bytes
tls.key:  62 bytes_

**Comment by aramase** [comment] 2020-05-20 16:07
@sainipankaj90k The changes for converting pkcs cert to pem format was merged recently - https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/82. We also have another change in the pipeline that changes the way to obtain certs and key for different formats - https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/98. After this change is merged and a release is cut this should work. I'll test it out and add a doc.

**Comment by sainipankaj90k** [comment] 2020-05-20 17:10
This is awesome, @aramase 
I am super happy that this work is already active. :)

**Comment by deyanp** [comment] 2020-05-22 11:31
@aramase , any idea when the new release will be published? How are new releases announced - can I subscribe to some feed?

**Comment by aramase** [comment] 2020-05-22 15:52
@deyanp We'll be cutting a new release today. If you are subscribed to the repo, you'll receive notification for the github release.

**Comment by aramase** [comment] 2020-05-26 22:47
@sainipankaj90k @deyanp We just cut a new release with all the changes included - https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/0.0.6. Please try it out and let us know if it resolves your issues.

**Comment by deyanp** [comment] 2020-05-27 10:09
@aramase I can confirm that the direct mapping of pfx (from Azure Key Vault) works now!
Spent 1h troubleshooting as I by mistake put `objectType: cert` which does not work, but `objectType: secret` works!

**Comment by sainipankaj90k** [comment] 2020-05-28 23:48
The mapping got changed but it doesn't seem like I found it was the same. My validation for ingress failed.

But yeah, not tls.crt is not empty for sure.

In the above question, either I can use it as cert or secret, but to push secret to vault I need the tls.key and tls.cer. How can I solve this one? 

I tried with whatever is mentioned above, since it was expected to be converted as 'PEM' file. But didn't work.

Can you please help me here?

**Comment by SatyKrish** [comment] 2020-06-15 11:28
@aramase tls example page not found.
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/sample/ingress-controller-tls/secretproviderclass-azure-tls.yaml

When I try to use `secretObjects[*].key` as `tls.secret`, secret sync failed with below error.

MountVolume.SetUp failed for volume "aks-helloworld" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = tls key is not supported. Only tls.key and tls.crt are supported.

**Comment by aramase** [comment] 2020-06-15 15:55
@SatyKrish Please refer this doc for how to configure tls - https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/sample/ingress-controller-tls. 

The sample `SecretProviderClass` to use is documented here - https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/sample/ingress-controller-tls#deploy-a-secretsproviderclass-resource

**Comment by SatyKrish** [comment] 2020-06-15 16:05
Thanks @aramase. I was able to resolve the error. The main confusion was around why certificate was referred as secret in your sample here - https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/sample/ingress-controller-tls#deploy-a-secretsproviderclass-resource

While `objectName: ingresscert` is created as certificate in KeyVault, it was referred to as 'objectType: secret' in the sample. After multiple tries I figured out that using 'objectType: secret' will sync to `tls.key` and `tls.crt` properly. It will be useful to add a comment about this reasoning.

**Comment by aramase** [comment] 2020-06-15 16:08
@SatyKrish We have the reasoning documented here - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md#getting-certificates-and-keys-using-azure-key-vault-provider. I'll also add a comment with reference to the link in the tls doc.

**Closed** 2020-06-19 19:17 UTC
Labels: documentation

**Comment by lin404** [comment] 2021-07-16 07:36
> We have the reasoning documented here - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md#getting-certificates-and-keys-using-azure-key-vault-provider.

The link leads to 404 page. Could you update it? Thank you.

**Comment by satr** [comment] 2021-12-13 15:34
The link above is not available. Maybe this article can help:
https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/getting-certs-and-keys/
Found it in [website-getting-started](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/website/content/en/getting-started/usage/_index.md) , in a comment to `objectType: secret`

**Comment by amarkevich** [comment] 2026-07-14 12:48
all the links provided above are broken
